#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0, rgba8) uniform writeonly image2D output_image;
layout(std430, set = 0, binding = 2) readonly buffer KnownOutput {
    vec4 color;
} known_output;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dimensions = imageSize(output_image);
    if (any(greaterThanEqual(pixel, dimensions))) {
        return;
    }
    imageStore(output_image, pixel, known_output.color);
}
